site_name: polars-bio
site_url: https://biodatageeks.org/polars-bio/
repo_url: https://github.com/biodatageeks/polars-bio
repo_name: biodatageeks/polars-bio

# Watch Python source files for auto-reload during development
watch:
  - polars_bio
nav:
  - 🏠 Home: index.md
  - 🏃🏼‍♂️ Quick start: quickstart.md
  - 🔨 Features:
      - Overview: features/index.md
      - Genomic operations: features/operations.md
      - Reading files: features/reading.md
      - Writing files: features/writing.md
      - SQL processing: features/sql.md
      - DataFrames support: features/dataframes.md
      - Cloud storage: features/cloud.md
      - Parallel processing: features/parallel.md
  - 📚 Tutorial: notebooks/tutorial.ipynb
  - ⚙️ API reference:
      - Overview: api/index.md
      - Reading files: api/reading.md
      - Genomic operations: api/operations.md
      - Writing files: api/writing.md
      - SQL interface: api/sql.md
      - Auxiliary: api/auxiliary.md
  - ❓ FAQ: faq.md
  - 🚀 Performance: supplement.md
  - 🛠️ Developers guide: developers.md
  - 🎤 Talks & presentations: talks.md
  - 📡 Contact: contact.md
  - 📖 Blog:
      - blog/index.md

plugins:
  - blog:
      post_date_format: full
      archive: false
      post_readtime: true
  - social
  - search
  - autorefs
  - mkdocs-jupyter:
      enabled: !ENV [ENABLE_JUPYTER, true]
      execute: false
      allow_errors: false
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
          options:
            docstring_style: google
  - markdown-exec:
      enabled: !ENV [ENABLE_MD_EXEC, true]
  - table-reader
  - mkdocs_matplotlib
  - exporter:
      formats:
        pdf:
          enabled: !ENV [ MKDOCS_EXPORTER_PDF, false ]
          concurrency: 8
#          stylesheets:
#            - resources/stylesheets/pdf.scss
#          covers:
#            front: resources/templates/covers/front.html.j2
#            back: resources/templates/covers/back.html.j2
          aggregator:
            enabled: true
            output: .well-known/site.pdf
            covers: all
  # Place glightbox last so it runs after other plugins
  - glightbox
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.tooltips
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - content.footnote.tooltips
  icon:
    repo: fontawesome/brands/github
extra:
  version:
    provider: mike
    default:
      - latest
  analytics:
    provider: google
    property: G-1M9PLLGBYS

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ..
      dedent_subsections: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - markdown.extensions.toc:
      baselevel: 1
      permalink: ""
