name: Publish docs via GitHub Pages
on:
  push:
   tags:
     - "*"
  workflow_dispatch:
jobs:
  build:
    env:
      JUPYTER_PLATFORM_DIRS: 1
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.12"
          enable-cache: true
      - run: uv sync --locked --all-extras --no-install-project
      - name: Install polars-bio
        run: uv run pip install polars-bio
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force --remote-branch gh-pages -f mkdocs.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
